require('dotenv').config()

const MONGODB_URI = process.env.MONGODB_URI
const PORT = process.env.PORT
const REQUEST_EXPIRATION_DAYS = process.env.REQUEST_EXPIRATION_DAYS
const REPORT_EXPIRATION_DAYS = process.env.REPORT_EXPIRATION_DAYS
const NODEMAILER_USER = process.env.NODEMAILER_USER
const NODEMAILER_PASS = process.env.NODEMAILER_PASS

module.exports = { MONGODB_URI, PORT, REQUEST_EXPIRATION_DAYS, REPORT_EXPIRATION_DAYS, NODEMAILER_USER, NODEMAILER_PASS }